### ISSUE TITLE
About the dataset release

### ISSUE THREAD

**Issue by zimuwangnlp** [IDEA-XL/MoleculeQA#1]
Dear authors,

Thank you for your brilliant work! Could you please let me know the time when the dataset will be released? Thank you.

**Comment by CiaoHe** [comment]
hi thx for your attention. We will update the dataset once it is accepted. Stay tune!

**Comment by CiaoHe** [comment]
plz refer to https://huggingface.co/datasets/hcaoaf/MoleculeQA
